CC=gcc
CFLAGS=-c -Wall

all: myshell asal toplam palindrom

myshell: myshell.c
	$(CC) myshell.c -o myshell

asal: asal.c 
	$(CC) asal.c -o asal

toplam: toplam.c
	$(CC) toplam.c -o toplam

palindrom: palindrom.c
	$(CC) palindrom.c -o palindrom

clean: 
	rm -rf *o myshell
